### ISSUE TITLE
pipenv recipe should use ADD

### ISSUE THREAD

**Issue by andyneff** [VisionSystemsInc/docker_recipes#2]
Why doesn't the pipenv recipe use `ADD` ranther than `ONBUILD RUN`? Add will make the script easier to read

**Comment by scott-vsi** [comment]
No good way to get the PIPENV_VERSION and the PIPENV_VIRTUALENV ONBUILD ARGs into the file.

**Comment by andyneff** [comment]
@scott-vsi What if we turned the build `ARG`'s into just environement variables instead? Then the script can just run using them like normal env vars? The `README` will need to be updated to reflect that
